[[asset]]
type = "Font"
path = "default_font"
id = 16777216

[asset.file_paths]
ttf = "Inter_24pt-Regular.ttf"

[[asset]]
type = "LuaScript"
path = "script/path/to/script"
id = 16777217

[asset.file_paths]
source = "script.lua"

[[asset]]
type = "LuaScript"
path = "script/audio_player"
id = 16777218

[asset.file_paths]
source = "audioPlayer.lua"

[[asset]]
type = "LuaScript"
path = "script/spin"
id = 16777219

[asset.file_paths]
source = "sprite.lua"

[[asset]]
type = "LuaScript"
path = "script/camera2D"
id = 16777220

[asset.file_paths]
source = "camera2D.lua"

[[asset]]
type = "AudioClip"
path = "forest"
id = 16777221

[[asset]]
type = "AudioClip"
path = "oiiai"
id = 16777222

[[asset]]
type = "Texture2D"
path = "texture/lobster"
id = 16777223

[[asset]]
type = "Texture2D"
path = "texture/duck"
id = 16777224

[[asset]]
type = "LuaScript"
path = "script/timer"
id = 16777225

[asset.file_paths]
source = "haha.lua"
binary = "asset.lda"

[[asset]]
type = "AudioClip"
path = "pop"
id = 16777226

[asset.file_paths]
binary = "asset.lda"

[[asset]]
type = "Texture2D"
path = "texture/what"
id = 16777227

[asset.file_paths]
binary = "asset.lda"

[ludens_assets]
version_patch = 0
version_minor = 0
version_major = 0

