[ludens_assets]
version_major = 0
version_minor = 0
version_patch = 0

[[asset]]
id = 16777216
type = "Font"
uri = "ld://asset/font/default_font"

[asset.path]
main = "../../Assets/font/Inter_24pt-Regular.lda"

[[asset]]
id = 16777217
uri = "ld://asset/script/script"
type = "LuaScript"

[asset.path]
main = "../../Assets/lua/script.lda"
source = "../../Assets/lua/script.lua"

[[asset]]
id = 16777218
type = "LuaScript"
uri = "ld://asset/script/audioPlayer"

[asset.path]
main = "../../Assets/lua/audioPlayer.lda"
source = "../../Assets/lua/audioPlayer.lua"

[[asset]]
id = 16777219
uri = "ld://asset/script/sprite.lda"
type = "LuaScript"

[asset.path]
main = "../../Assets/lua/sprite.lda"
source = "../../Assets/lua/sprite.lua"

[[asset]]
id = 16777220
type = "LuaScript"
uri = "ld://asset/script/camera2D"

[asset.path]
main = "../../Assets/lua/camera2D.lda"
source = "../../Assets/lua/camera2D.lua"

[[asset]]
id = 16777221
type = "AudioClip"
uri = "ld://asset/audio/forest"

[asset.path]
main = "../../Assets/audio/forest.lda"

[[asset]]
id = 16777222
uri = "ld://asset/audio/oiiai"
type = "AudioClip"

[asset.path]
main = "../../Assets/audio/oiiai.lda"

[[asset]]
id = 16777223
uri = "ld://asset/texture/lobster"
type = "Texture2D"

[asset.path]
main = "../../Texture/lobster.lda"

[[asset]]
id = 16777224
uri = "ld://asset/texture/duck"
type = "Texture2D"

[asset.path]
main = "../../Texture/duck.lda"

[[asset]]
id = 16777226
type = "UITemplate"
uri = "ld://asset/ui/hud"

[asset.path]
main = "../../Assets/ui/hud.toml"
source = "../../Assets/ui/hud.lua"

