[ludens_scene]
version_major = 0
version_minor = 0
version_patch = 0

[hierarchy]
33554438 = [33554444]
33554440 = [33554445]
33554439 = [33554440]

[[component]]
id = 33554438
screen_layer_id = 67108865
region = {x = 50.0, h = 100.0, y = 0.0, w = 100.0}
type = "Sprite2D"
name = "Lob"
script_id = 16777219
pivot = {x = 50.0, y = 50.0}
transform = {position = {x = -61.6725, y = 234.139}, scale = {x = 1.0, y = 1.0}, rotation = 0.0}
texture_2d_id = 16777223
z_depth = 7

[[component]]
id = 33554444
type = "Camera2D"
name = "cameraL"
zoom = 1.0
script_id = 16777220
viewport = {h = 1.0, x = 0.0, y = 0.0, w = 1.0}
transform = {position = {x = 0.0, y = 0.0}, scale = {x = 1.0, y = 1.0}, rotation = 0.0}
extent = {x = 1117.0, y = 565.6}

[[component]]
id = 33554439
screen_layer_id = 67108865
region = {x = 50.0, h = 230.0, y = 50.0, w = 250.0}
type = "Sprite2D"
name = "Duck1"
script_id = 0
pivot = {x = 0.0, y = 0.0}
transform = {position = {x = -67.687, y = 48.8661}, scale = {x = 1.07244, y = 1.07244}, rotation = 0.0}
texture_2d_id = 16777224
z_depth = 10

[[component]]
id = 33554440
screen_layer_id = 67108865
region = {h = 100.0, x = 0.0, y = 0.0, w = 100.0}
type = "Sprite2D"
name = "Lob2"
script_id = 0
pivot = {x = 50.0, y = 50.0}
transform = {position = {x = 304.12, y = 194.232}, scale = {x = 1.0, y = 1.0}, rotation = 0.0}
texture_2d_id = 16777223
z_depth = 7

[[component]]
id = 33554445
screen_layer_id = 67108865
region = {x = 0.0, h = 100.0, y = 0.0, w = 100.0}
type = "Sprite2D"
name = "Lob3"
script_id = 0
pivot = {x = 50.0, y = 50.0}
transform = {position = {x = -33.5187, y = -48.3437}, scale = {x = 1.0, y = 1.0}, rotation = 0.0}
texture_2d_id = 16777223
z_depth = 5

[[component]]
id = 33554441
screen_layer_id = 67108865
region = {x = 230.0, h = 230.0, y = 0.0, w = 230.0}
type = "Sprite2D"
name = "Duck2"
script_id = 0
pivot = {x = 0.0, y = 0.0}
transform = {position = {x = -681.849, y = 2.64955}, scale = {x = 1.0, y = 1.0}, rotation = 0.0}
texture_2d_id = 16777224
z_depth = 9

[[component]]
id = 33554443
type = "ScreenUI"
ui_template_id = 16777226
name = "HUD"
script_id = 0

