[ludens_scene]
version_major = 0
version_minor = 0
version_patch = 0

[hierarchy]
[[component]]
id = 33554437
type = "Camera2D"
name = "Camera2DComponent"
zoom = 1.0
script_id = 0
viewport = {h = 1.0, x = 0.0, y = 0.0, w = 1.0}
transform = {position = {x = 0.0, y = 0.0}, scale = {x = 1.0, y = 1.0}, rotation = 0.0}
extent = {x = 1117.0, y = 565.6}

